2016-04-17 13:20:39 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: ÐžÐ±ÑŠÐµÐºÑ‚ ÑƒÐ¶Ðµ Ð·Ð°ÐºÑ€Ñ‹Ñ‚
The object is already closed [90007-191]
2016-04-17 13:20:39 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: ÐžÐ±ÑŠÐµÐºÑ‚ ÑƒÐ¶Ðµ Ð·Ð°ÐºÑ€Ñ‹Ñ‚
The object is already closed [90007-191]
2016-04-17 13:20:39 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: ÐžÐ±ÑŠÐµÐºÑ‚ ÑƒÐ¶Ðµ Ð·Ð°ÐºÑ€Ñ‹Ñ‚
The object is already closed [90007-191]
2016-04-17 16:11:21 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: ÐžÐ±ÑŠÐµÐºÑ‚ ÑƒÐ¶Ðµ Ð·Ð°ÐºÑ€Ñ‹Ñ‚
The object is already closed [90007-191]
2016-04-17 16:11:21 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: ÐžÐ±ÑŠÐµÐºÑ‚ ÑƒÐ¶Ðµ Ð·Ð°ÐºÑ€Ñ‹Ñ‚
The object is already closed [90007-191]
2016-04-17 16:11:21 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: ÐžÐ±ÑŠÐµÐºÑ‚ ÑƒÐ¶Ðµ Ð·Ð°ÐºÑ€Ñ‹Ñ‚
The object is already closed [90007-191]
2016-04-17 16:13:32 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: ÐžÐ±ÑŠÐµÐºÑ‚ ÑƒÐ¶Ðµ Ð·Ð°ÐºÑ€Ñ‹Ñ‚
The object is already closed [90007-191]
2016-04-17 16:13:53 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: ÐžÐ±ÑŠÐµÐºÑ‚ ÑƒÐ¶Ðµ Ð·Ð°ÐºÑ€Ñ‹Ñ‚
The object is already closed [90007-191]
2016-04-17 16:13:54 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: ÐžÐ±ÑŠÐµÐºÑ‚ ÑƒÐ¶Ðµ Ð·Ð°ÐºÑ€Ñ‹Ñ‚
The object is already closed [90007-191]
2016-04-17 16:13:54 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: ÐžÐ±ÑŠÐµÐºÑ‚ ÑƒÐ¶Ðµ Ð·Ð°ÐºÑ€Ñ‹Ñ‚
The object is already closed [90007-191]
2016-04-17 16:13:54 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: ÐžÐ±ÑŠÐµÐºÑ‚ ÑƒÐ¶Ðµ Ð·Ð°ÐºÑ€Ñ‹Ñ‚
The object is already closed [90007-191]
2016-04-17 16:14:33 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: ÐžÐ±ÑŠÐµÐºÑ‚ ÑƒÐ¶Ðµ Ð·Ð°ÐºÑ€Ñ‹Ñ‚
The object is already closed [90007-191]
2016-04-17 16:14:33 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: ÐžÐ±ÑŠÐµÐºÑ‚ ÑƒÐ¶Ðµ Ð·Ð°ÐºÑ€Ñ‹Ñ‚
The object is already closed [90007-191]
2016-04-17 16:14:33 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: ÐžÐ±ÑŠÐµÐºÑ‚ ÑƒÐ¶Ðµ Ð·Ð°ÐºÑ€Ñ‹Ñ‚
The object is already closed [90007-191]
2016-04-17 16:15:24 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: ÐžÐ±ÑŠÐµÐºÑ‚ ÑƒÐ¶Ðµ Ð·Ð°ÐºÑ€Ñ‹Ñ‚
The object is already closed [90007-191]
2016-04-17 17:20:33 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: ÐžÐ±ÑŠÐµÐºÑ‚ ÑƒÐ¶Ðµ Ð·Ð°ÐºÑ€Ñ‹Ñ‚
The object is already closed [90007-191]
2016-04-17 17:20:33 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: ÐžÐ±ÑŠÐµÐºÑ‚ ÑƒÐ¶Ðµ Ð·Ð°ÐºÑ€Ñ‹Ñ‚
The object is already closed [90007-191]
2016-04-17 17:20:33 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: ÐžÐ±ÑŠÐµÐºÑ‚ ÑƒÐ¶Ðµ Ð·Ð°ÐºÑ€Ñ‹Ñ‚
The object is already closed [90007-191]
2016-04-17 17:44:04 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: ÐžÐ±ÑŠÐµÐºÑ‚ ÑƒÐ¶Ðµ Ð·Ð°ÐºÑ€Ñ‹Ñ‚
The object is already closed [90007-191]
2016-04-17 17:48:11 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: ÐžÐ±ÑŠÐµÐºÑ‚ ÑƒÐ¶Ðµ Ð·Ð°ÐºÑ€Ñ‹Ñ‚
The object is already closed [90007-191]
2016-04-23 12:52:40 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: ÐžÐ±ÑŠÐµÐºÑ‚ ÑƒÐ¶Ðµ Ð·Ð°ÐºÑ€Ñ‹Ñ‚
The object is already closed [90007-191]
2016-04-23 12:52:40 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: ÐžÐ±ÑŠÐµÐºÑ‚ ÑƒÐ¶Ðµ Ð·Ð°ÐºÑ€Ñ‹Ñ‚
The object is already closed [90007-191]
2016-04-23 12:52:40 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: ÐžÐ±ÑŠÐµÐºÑ‚ ÑƒÐ¶Ðµ Ð·Ð°ÐºÑ€Ñ‹Ñ‚
The object is already closed [90007-191]
2016-04-23 13:07:16 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: ÐžÐ±ÑŠÐµÐºÑ‚ ÑƒÐ¶Ðµ Ð·Ð°ÐºÑ€Ñ‹Ñ‚
The object is already closed [90007-191]
2016-04-23 13:07:40 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: ÐžÐ±ÑŠÐµÐºÑ‚ ÑƒÐ¶Ðµ Ð·Ð°ÐºÑ€Ñ‹Ñ‚
The object is already closed [90007-191]
2016-04-23 13:07:40 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: ÐžÐ±ÑŠÐµÐºÑ‚ ÑƒÐ¶Ðµ Ð·Ð°ÐºÑ€Ñ‹Ñ‚
The object is already closed [90007-191]
2016-04-23 13:07:40 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: ÐžÐ±ÑŠÐµÐºÑ‚ ÑƒÐ¶Ðµ Ð·Ð°ÐºÑ€Ñ‹Ñ‚
The object is already closed [90007-191]
2016-04-23 13:15:25 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: ÐžÐ±ÑŠÐµÐºÑ‚ ÑƒÐ¶Ðµ Ð·Ð°ÐºÑ€Ñ‹Ñ‚
The object is already closed [90007-191]
2016-04-23 13:15:26 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: ÐžÐ±ÑŠÐµÐºÑ‚ ÑƒÐ¶Ðµ Ð·Ð°ÐºÑ€Ñ‹Ñ‚
The object is already closed [90007-191]
2016-04-23 13:15:39 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: ÐžÐ±ÑŠÐµÐºÑ‚ ÑƒÐ¶Ðµ Ð·Ð°ÐºÑ€Ñ‹Ñ‚
The object is already closed [90007-191]
2016-04-23 13:15:39 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: ÐžÐ±ÑŠÐµÐºÑ‚ ÑƒÐ¶Ðµ Ð·Ð°ÐºÑ€Ñ‹Ñ‚
The object is already closed [90007-191]
2016-04-23 13:15:39 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: ÐžÐ±ÑŠÐµÐºÑ‚ ÑƒÐ¶Ðµ Ð·Ð°ÐºÑ€Ñ‹Ñ‚
The object is already closed [90007-191]
2016-04-23 14:36:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: ÐžÐ±ÑŠÐµÐºÑ‚ ÑƒÐ¶Ðµ Ð·Ð°ÐºÑ€Ñ‹Ñ‚
The object is already closed [90007-191]
2016-04-23 14:36:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: ÐžÐ±ÑŠÐµÐºÑ‚ ÑƒÐ¶Ðµ Ð·Ð°ÐºÑ€Ñ‹Ñ‚
The object is already closed [90007-191]
2016-04-23 14:37:33 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: ÐžÐ±ÑŠÐµÐºÑ‚ ÑƒÐ¶Ðµ Ð·Ð°ÐºÑ€Ñ‹Ñ‚
The object is already closed [90007-191]
2016-04-23 14:37:33 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: ÐžÐ±ÑŠÐµÐºÑ‚ ÑƒÐ¶Ðµ Ð·Ð°ÐºÑ€Ñ‹Ñ‚
The object is already closed [90007-191]
2016-04-23 14:37:33 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: ÐžÐ±ÑŠÐµÐºÑ‚ ÑƒÐ¶Ðµ Ð·Ð°ÐºÑ€Ñ‹Ñ‚
The object is already closed [90007-191]
2016-04-23 14:37:52 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: ÐžÐ±ÑŠÐµÐºÑ‚ ÑƒÐ¶Ðµ Ð·Ð°ÐºÑ€Ñ‹Ñ‚
The object is already closed [90007-191]
2016-04-23 14:38:07 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: ÐžÐ±ÑŠÐµÐºÑ‚ ÑƒÐ¶Ðµ Ð·Ð°ÐºÑ€Ñ‹Ñ‚
The object is already closed [90007-191]
2016-04-23 14:38:07 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: ÐžÐ±ÑŠÐµÐºÑ‚ ÑƒÐ¶Ðµ Ð·Ð°ÐºÑ€Ñ‹Ñ‚
The object is already closed [90007-191]
2016-04-23 14:38:07 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: ÐžÐ±ÑŠÐµÐºÑ‚ ÑƒÐ¶Ðµ Ð·Ð°ÐºÑ€Ñ‹Ñ‚
The object is already closed [90007-191]
2016-04-23 14:41:51 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: ÐžÐ±ÑŠÐµÐºÑ‚ ÑƒÐ¶Ðµ Ð·Ð°ÐºÑ€Ñ‹Ñ‚
The object is already closed [90007-191]
2016-04-23 15:37:18 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: ÐžÐ±ÑŠÐµÐºÑ‚ ÑƒÐ¶Ðµ Ð·Ð°ÐºÑ€Ñ‹Ñ‚
The object is already closed [90007-191]
2016-04-23 15:37:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: ÐžÐ±ÑŠÐµÐºÑ‚ ÑƒÐ¶Ðµ Ð·Ð°ÐºÑ€Ñ‹Ñ‚
The object is already closed [90007-191]
2016-04-23 15:37:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: ÐžÐ±ÑŠÐµÐºÑ‚ ÑƒÐ¶Ðµ Ð·Ð°ÐºÑ€Ñ‹Ñ‚
The object is already closed [90007-191]
2016-04-23 17:19:34 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: ÐžÐ±ÑŠÐµÐºÑ‚ ÑƒÐ¶Ðµ Ð·Ð°ÐºÑ€Ñ‹Ñ‚
The object is already closed [90007-191]
2016-04-23 17:19:34 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: ÐžÐ±ÑŠÐµÐºÑ‚ ÑƒÐ¶Ðµ Ð·Ð°ÐºÑ€Ñ‹Ñ‚
The object is already closed [90007-191]
2016-04-23 17:19:34 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: ÐžÐ±ÑŠÐµÐºÑ‚ ÑƒÐ¶Ðµ Ð·Ð°ÐºÑ€Ñ‹Ñ‚
The object is already closed [90007-191]
2016-04-23 17:20:18 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Ð¢Ð°Ð±Ð»Ð¸Ñ†Ð° "PERSONDATAWHERE" Ð½Ðµ Ð½Ð°Ð¹Ð´ÐµÐ½Ð°
Table "PERSONDATAWHERE" not found; SQL statement:
select * from PersonDataWHERE pd_login = 'Veron' AND pd_password = '12345' [42102-191]
2016-04-23 17:21:58 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Ð¢Ð°Ð±Ð»Ð¸Ñ†Ð° "PERSONDATAWHERE" Ð½Ðµ Ð½Ð°Ð¹Ð´ÐµÐ½Ð°
Table "PERSONDATAWHERE" not found; SQL statement:
select pd_d_last_call, pd_d_birthday from PersonDataWHERE pd_login = 'Veron' AND pd_password = '12345' [42102-191]
2016-04-23 17:23:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Ð¢Ð°Ð±Ð»Ð¸Ñ†Ð° "PERSONDATAWHERE" Ð½Ðµ Ð½Ð°Ð¹Ð´ÐµÐ½Ð°
Table "PERSONDATAWHERE" not found; SQL statement:
select pd_d_last_call, pd_d_birthday from PersonDataWHERE pd_login = 'Veron' AND pd_password = '12345' [42102-191]
2016-04-23 17:23:53 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Ð¢Ð°Ð±Ð»Ð¸Ñ†Ð° "PERSONDATAWHERE" Ð½Ðµ Ð½Ð°Ð¹Ð´ÐµÐ½Ð°
Table "PERSONDATAWHERE" not found; SQL statement:
select pd_d_last_call, pd_d_birthday from PersonDataWHERE pd_login = 'Veron' AND pd_password = '12345' [42102-191]
2016-04-23 17:26:47 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: ÐžÐ±ÑŠÐµÐºÑ‚ ÑƒÐ¶Ðµ Ð·Ð°ÐºÑ€Ñ‹Ñ‚
The object is already closed [90007-191]
2016-04-23 17:26:48 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: ÐžÐ±ÑŠÐµÐºÑ‚ ÑƒÐ¶Ðµ Ð·Ð°ÐºÑ€Ñ‹Ñ‚
The object is already closed [90007-191]
2016-04-23 17:31:32 database: flush
org.h2.message.DbException: Ð’Ð½ÑƒÑ‚Ñ€ÐµÐ½Ð½Ñ�Ñ� Ð¾ÑˆÐ¸Ð±ÐºÐ°: "java.lang.IllegalStateException: The file is locked: nio:C:/test/testbase.mv.db [1.4.191/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/test/testbase.mv.db [1.4.191/7]" [50000-191]
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:295)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:94)
	at org.h2.mvstore.MVStore.panic(MVStore.java:373)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:356)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2888)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:154)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:99)
	at org.h2.engine.Database.getPageStore(Database.java:2460)
	at org.h2.engine.Database.open(Database.java:692)
	at org.h2.engine.Database.openDatabase(Database.java:270)
	at org.h2.engine.Database.<init>(Database.java:264)
	at org.h2.engine.Engine.openSession(Engine.java:65)
	at org.h2.engine.Engine.openSession(Engine.java:175)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:153)
	at org.h2.engine.Engine.createSession(Engine.java:136)
	at org.h2.engine.Engine.createSession(Engine.java:28)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:349)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:107)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at DataBase.DataBase.Connect(DataBase.java:27)
	at DataBase.main.main(main.java:13)
Caused by: org.h2.jdbc.JdbcSQLException: Ð’Ð½ÑƒÑ‚Ñ€ÐµÐ½Ð½Ñ�Ñ� Ð¾ÑˆÐ¸Ð±ÐºÐ°: "java.lang.IllegalStateException: The file is locked: nio:C:/test/testbase.mv.db [1.4.191/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/test/testbase.mv.db [1.4.191/7]" [50000-191]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 25 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:C:/test/testbase.mv.db [1.4.191/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:773)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:342)
	... 20 more
2016-04-23 17:32:03 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: ÐžÐ±ÑŠÐµÐºÑ‚ ÑƒÐ¶Ðµ Ð·Ð°ÐºÑ€Ñ‹Ñ‚
The object is already closed [90007-191]
2016-04-23 17:32:03 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: ÐžÐ±ÑŠÐµÐºÑ‚ ÑƒÐ¶Ðµ Ð·Ð°ÐºÑ€Ñ‹Ñ‚
The object is already closed [90007-191]
2016-04-23 17:32:03 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: ÐžÐ±ÑŠÐµÐºÑ‚ ÑƒÐ¶Ðµ Ð·Ð°ÐºÑ€Ñ‹Ñ‚
The object is already closed [90007-191]
2016-04-23 17:32:17 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: ÐžÐ±ÑŠÐµÐºÑ‚ ÑƒÐ¶Ðµ Ð·Ð°ÐºÑ€Ñ‹Ñ‚
The object is already closed [90007-191]
2016-04-23 17:32:18 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: ÐžÐ±ÑŠÐµÐºÑ‚ ÑƒÐ¶Ðµ Ð·Ð°ÐºÑ€Ñ‹Ñ‚
The object is already closed [90007-191]
2016-04-23 17:32:43 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: ÐžÐ±ÑŠÐµÐºÑ‚ ÑƒÐ¶Ðµ Ð·Ð°ÐºÑ€Ñ‹Ñ‚
The object is already closed [90007-191]
2016-04-23 17:32:43 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: ÐžÐ±ÑŠÐµÐºÑ‚ ÑƒÐ¶Ðµ Ð·Ð°ÐºÑ€Ñ‹Ñ‚
The object is already closed [90007-191]
2016-04-23 17:32:43 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: ÐžÐ±ÑŠÐµÐºÑ‚ ÑƒÐ¶Ðµ Ð·Ð°ÐºÑ€Ñ‹Ñ‚
The object is already closed [90007-191]
2016-04-23 17:32:50 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: ÐžÐ±ÑŠÐµÐºÑ‚ ÑƒÐ¶Ðµ Ð·Ð°ÐºÑ€Ñ‹Ñ‚
The object is already closed [90007-191]
2016-04-23 17:32:50 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: ÐžÐ±ÑŠÐµÐºÑ‚ ÑƒÐ¶Ðµ Ð·Ð°ÐºÑ€Ñ‹Ñ‚
The object is already closed [90007-191]
2016-04-23 17:36:33 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: ÐžÐ±ÑŠÐµÐºÑ‚ ÑƒÐ¶Ðµ Ð·Ð°ÐºÑ€Ñ‹Ñ‚
The object is already closed [90007-191]
2016-04-23 17:36:33 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: ÐžÐ±ÑŠÐµÐºÑ‚ ÑƒÐ¶Ðµ Ð·Ð°ÐºÑ€Ñ‹Ñ‚
The object is already closed [90007-191]
2016-04-23 17:36:33 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: ÐžÐ±ÑŠÐµÐºÑ‚ ÑƒÐ¶Ðµ Ð·Ð°ÐºÑ€Ñ‹Ñ‚
The object is already closed [90007-191]
